;; key bindings
(bind-key "C-c h" 'help-for-help)
(bind-key "C-x C-c" 'server-edit)
(bind-key "C-h" 'delete-backward-char)
(bind-key "C-@" 'mark-word)
(bind-key "C-x l" 'goto-line)
(bind-key "C-x j" 'open-junk-file)
(bind-key "C-x C-g" 'ag)
(bind-key "C-;" 'helm-mini)
(bind-key "C-:" 'helm-projectile)
(bind-key "M-x" 'helm-M-x)
(bind-key "C-x C-f" 'helm-find-files)
(bind-key "M-y" 'helm-show-kill-ring)
(bind-key "C-x b" 'helm-buffers-list)
(bind-key "C-x p" 'helm-ghq)
(bind-key "C-x y" 'helm-bundle-show)
